pool:
  name: Test # 构建代理名称

trigger:
  branches:
    include: # 可以触发的分支
      - master

variables: # 自定义变量
  - name: branchNameLower
    value: $[lower(variables['Build.SourceBranchName'])]
  - name: serviceName
    value: test

jobs:
  - job: prepare
    displayName: 拉取相关代码仓库
    workspace:
      clean: all
    steps:
      - checkout: self # 拉取本仓库代码
      - script: |
          echo ${branchNameLower}
          echo ${serviceName}
